#!/usr/bin/env node
// Copies the built site into the publish repository and commits it there.
//
//   npm run build         write dist/
//   npm run publish:web   copy dist/index.html into the checkout and commit
//
// The page lands at static/index.html in the publish repository. Its own build
// copies static/ into dist/, which is the directory Cloudflare Pages serves,
// so dist/ is a build artifact there and is not committed.
//
// The push is left to you, since this script has no credentials.
//
// Target directory, in order of precedence:
//   1. the first argument, `npm run publish:web -- ../somewhere-else`
//   2. $CCCC_WEB_DIR
//   3. ../cccc-web, beside this repository

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { REPO_ROOT, c } from './lib.mjs';

const DIST = path.join(REPO_ROOT, 'dist');
const SOURCE = path.join(DIST, 'index.html');

// Anything else in dist/ that the page links to and the publish repository
// therefore has to serve. The page itself stays one self contained file; the
// deck is a download beside it.
const EXTRAS = ['claude-code-crash-course.pdf'];

function resolveTarget() {
  const arg = process.argv[2];
  if (arg) return path.resolve(arg);
  if (process.env.CCCC_WEB_DIR) return path.resolve(process.env.CCCC_WEB_DIR);
  return path.resolve(REPO_ROOT, '..', 'cccc-web');
}

function git(dir, args) {
  return execFileSync('git', args, { cwd: dir, encoding: 'utf8' }).trim();
}

function main() {
  if (!fs.existsSync(SOURCE)) {
    console.error(c.red('publish:web') + ': dist/index.html is missing. Run `npm run build` first.');
    process.exit(1);
  }

  const target = resolveTarget();
  if (!fs.existsSync(path.join(target, '.git'))) {
    console.error(c.red('publish:web') + ': no git checkout at ' + target);
    console.error('Clone it first, or pass the path:');
    console.error('  npm run publish:web -- /path/to/cccc-web');
    process.exit(1);
  }

  const outDir = path.join(target, 'static');
  fs.mkdirSync(outDir, { recursive: true });
  fs.copyFileSync(SOURCE, path.join(outDir, 'index.html'));

  for (const name of EXTRAS) {
    const from = path.join(DIST, name);
    if (fs.existsSync(from)) fs.copyFileSync(from, path.join(outDir, name));
    else console.warn(c.dim('publish:web') + ': ' + name + ' is not in dist/, skipping.');
  }

  const status = git(target, ['status', '--porcelain']);
  if (!status) {
    console.log(c.dim('publish:web') + ': ' + target + ' is already up to date. Nothing to commit.');
    return;
  }

  const bytes = fs.statSync(SOURCE).size;
  const stamp = new Date().toISOString().slice(0, 10);
  git(target, ['add', '-A']);
  git(target, [
    'commit',
    '-m',
    'Publish the field manual, ' + stamp,
    '-m',
    'Generated by npm run build in the crash course repository. ' +
      Math.round(bytes / 1024) +
      ' KB, one self contained page.',
  ]);

  const copied = EXTRAS.filter((n) => fs.existsSync(path.join(outDir, n)));
  console.log(c.green(c.bold('published')) + ': ' + path.join(outDir, 'index.html'));
  for (const name of copied) console.log(c.dim('          plus: ') + path.join(outDir, name));
  console.log(c.dim('Now push it:'));
  console.log(c.dim('  cd ' + target + ' && git push'));
}

main();
